# R8 keep rules.
#
# The guiding rule here: do not re-state what a library already ships. Ktor,
# coroutines, kotlinx.serialization, Media3, OkHttp and WorkManager all publish
# consumer rules inside their artifacts (META-INF/com.android.tools/r8/*.pro, or
# proguard.txt in the AAR), and AGP generates keep rules for everything named in
# the merged manifest — Application, Activity and both Services. Restating any
# of that as `-keep class <package>.** { *; }` does not make the app safer; it
# just removes those classes from R8's reach. Play's "R8 optimization" insight
# measured the result of the previous rules here: 36% optimized, obfuscated and
# shrunk.

# --- kotlinx.serialization -------------------------------------------------
# Nothing needed. The plugin generates a serializer per @Serializable class and
# the runtime's own R8 rules keep them; field names travel as strings inside the
# generated descriptor, so obfuscating the model classes is safe.

# --- Ktor ------------------------------------------------------------------
# Ktor ships no consumer rules. Its one reflective seam is engine discovery via
# ServiceLoader, which only runs for the no-argument `HttpClient()`; the Android
# client names OkHttp explicitly (see Platform.android.kt), so there is nothing
# to keep. These suppress warnings about optional integrations we do not bundle.
-dontwarn kotlinx.atomicfu.**
-dontwarn io.netty.**
-dontwarn com.typesafe.**
-dontwarn org.slf4j.**

# --- Generated by AGP ------------------------------------------------------
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
